---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 30
        timeout: 60

    - name: "install python for Ansible."
      become: true
      apt:
        name: python3
        update_cache: yes

  environment:
    - NODE_ENV: production
    - VERSION: "1"
    - ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    - TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    - TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    - TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"

  roles:
    - deploy
